// Auto-generated by scripts/fetch-place-photos.ts
// Do not edit manually. Re-run the script to refresh.

export type ShopPhotos = {
  place_id: string;
  google_maps_uri?: string;
  rating?: number;
  user_rating_count?: number;
  image_paths: string[];
  attributions: string[];
};

export const shopPhotos: Record<string, ShopPhotos> = {
  "tomorrowland-shibuya": {
    "place_id": "ChIJTZhjx6eMGGARx7P6Drq03XQ",
    "google_maps_uri": "https://maps.google.com/?cid=8421085589460923335&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA",
    "rating": 3.9,
    "user_rating_count": 113,
    "image_paths": [
      "images/shops/tomorrowland-shibuya/1.jpg",
      "images/shops/tomorrowland-shibuya/2.jpg",
      "images/shops/tomorrowland-shibuya/3.jpg"
    ],
    "attributions": [
      "トゥモローランド 渋谷本店"
    ]
  },
  "ships-shibuya": {
    "place_id": "ChIJSe_8lKiMGGARMhVfAf60o-g",
    "google_maps_uri": "https://maps.google.com/?cid=16763441241040819506&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA",
    "rating": 4.1,
    "user_rating_count": 140,
    "image_paths": [
      "images/shops/ships-shibuya/1.jpg",
      "images/shops/ships-shibuya/2.jpg",
      "images/shops/ships-shibuya/3.jpg"
    ],
    "attributions": [
      "にゃんこゴールド",
      "SHIPS 渋谷店"
    ]
  },
  "adam-et-rope-shibuya-parco": {
    "place_id": "ChIJ2VQC46iMGGAR3qugWC-5Shg",
    "google_maps_uri": "https://maps.google.com/?cid=1750415018188385246&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA",
    "rating": 4.3,
    "user_rating_count": 3,
    "image_paths": [
      "images/shops/adam-et-rope-shibuya-parco/1.jpg",
      "images/shops/adam-et-rope-shibuya-parco/2.jpg",
      "images/shops/adam-et-rope-shibuya-parco/3.jpg"
    ],
    "attributions": [
      "Torben Mauch",
      "めーだい"
    ]
  },
  "studious-jinnan": {
    "place_id": "ChIJ9XBmOK-MGGARmEf75bx8Gmc",
    "google_maps_uri": "https://maps.google.com/?cid=7429387686055200664&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA",
    "rating": 4.4,
    "user_rating_count": 64,
    "image_paths": [
      "images/shops/studious-jinnan/1.jpg",
      "images/shops/studious-jinnan/2.jpg",
      "images/shops/studious-jinnan/3.jpg"
    ],
    "attributions": [
      "MOTOAKI EBISUI",
      "にゃんこゴールド",
      "O and N"
    ]
  },
  "nano-universe-jinnan": {
    "place_id": "ChIJAQBwwqiMGGARicRwxpFY0LU",
    "google_maps_uri": "https://maps.google.com/?cid=13101068699143554185&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA",
    "rating": 3.6,
    "user_rating_count": 84,
    "image_paths": [
      "images/shops/nano-universe-jinnan/1.jpg",
      "images/shops/nano-universe-jinnan/2.jpg",
      "images/shops/nano-universe-jinnan/3.jpg"
    ],
    "attributions": [
      "H. T",
      "jpn qc",
      "LENNON 10"
    ]
  },
  "beams-men-shibuya": {
    "place_id": "ChIJj2SEzKiMGGARofu5OyrOfyw",
    "google_maps_uri": "https://maps.google.com/?cid=3206508140497075105&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA",
    "rating": 4.4,
    "user_rating_count": 755,
    "image_paths": [
      "images/shops/beams-men-shibuya/1.jpg",
      "images/shops/beams-men-shibuya/2.jpg",
      "images/shops/beams-men-shibuya/3.jpg"
    ],
    "attributions": [
      "ビームス メン 渋谷",
      "JB"
    ]
  },
  "united-arrows-scramble-square": {
    "place_id": "ChIJvWXKpRKLGGAReFHXvWWjZt4",
    "google_maps_uri": "https://maps.google.com/?cid=16025675981416518008&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA",
    "rating": 3.4,
    "user_rating_count": 51,
    "image_paths": [
      "images/shops/united-arrows-scramble-square/1.jpg",
      "images/shops/united-arrows-scramble-square/2.jpg",
      "images/shops/united-arrows-scramble-square/3.jpg"
    ],
    "attributions": [
      "はるか",
      "2019 dearsilence",
      "MU"
    ]
  },
  "freaks-store-shibuya": {
    "place_id": "ChIJUzfHlaiMGGARpLxcCvZnorQ",
    "google_maps_uri": "https://maps.google.com/?cid=13016080179487620260&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA",
    "rating": 3.9,
    "user_rating_count": 333,
    "image_paths": [
      "images/shops/freaks-store-shibuya/1.jpg",
      "images/shops/freaks-store-shibuya/2.jpg",
      "images/shops/freaks-store-shibuya/3.jpg"
    ],
    "attributions": [
      "村長智",
      "にゃんこゴールド",
      "Takashi Minakuchi"
    ]
  },
  "417-edifice-shibuya": {
    "place_id": "ChIJy0oY0qiMGGARvbOmr-WQyn8",
    "google_maps_uri": "https://maps.google.com/?cid=9208331704281248701&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA",
    "rating": 4.4,
    "user_rating_count": 56,
    "image_paths": [
      "images/shops/417-edifice-shibuya/1.jpg",
      "images/shops/417-edifice-shibuya/2.jpg",
      "images/shops/417-edifice-shibuya/3.jpg"
    ],
    "attributions": [
      "417 EDIFICE 渋谷店"
    ]
  },
  "midwest-tokyo": {
    "place_id": "ChIJVxMzN6-MGGARFYlansvAz9w",
    "google_maps_uri": "https://maps.google.com/?cid=15911147989290879253&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA",
    "rating": 3.7,
    "user_rating_count": 26,
    "image_paths": [
      "images/shops/midwest-tokyo/1.jpg",
      "images/shops/midwest-tokyo/2.jpg",
      "images/shops/midwest-tokyo/3.jpg"
    ],
    "attributions": [
      "MIDWEST TOKYO",
      "s s",
      "Hiroshi Koizümi"
    ]
  },
  "lechoppe-miyashita-park": {
    "place_id": "ChIJyxFifOyNGGARa6vE2wDB2eQ",
    "google_maps_uri": "https://maps.google.com/?cid=16490423720025041771&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA",
    "rating": 4.2,
    "user_rating_count": 13,
    "image_paths": [
      "images/shops/lechoppe-miyashita-park/1.jpg",
      "images/shops/lechoppe-miyashita-park/2.jpg",
      "images/shops/lechoppe-miyashita-park/3.jpg"
    ],
    "attributions": [
      "t s",
      "Kapskugelカップスクーゲル",
      "シンイチ"
    ]
  },
  "fan-shibuya-parco": {
    "place_id": "ChIJN4VxEw-NGGARyrvexzcsHPQ",
    "google_maps_uri": "https://maps.google.com/?cid=17589982862690401226&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA",
    "rating": 4.7,
    "user_rating_count": 3,
    "image_paths": [
      "images/shops/fan-shibuya-parco/1.jpg",
      "images/shops/fan-shibuya-parco/2.jpg",
      "images/shops/fan-shibuya-parco/3.jpg"
    ],
    "attributions": [
      "FAN"
    ]
  },
  "garden-shibuya": {
    "place_id": "ChIJp6L5v6iMGGARFbfTb6gkQPI",
    "google_maps_uri": "https://maps.google.com/?cid=17455992461537294101&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA",
    "rating": 4.8,
    "user_rating_count": 8,
    "image_paths": [
      "images/shops/garden-shibuya/1.jpg"
    ],
    "attributions": [
      "ずんだもん"
    ]
  },
  "ware-mo-kou": {
    "place_id": "ChIJAQAw66iMGGARnkJKheCU5UI",
    "google_maps_uri": "https://maps.google.com/?cid=4820422668199805598&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA",
    "rating": 3.1,
    "user_rating_count": 71,
    "image_paths": [
      "images/shops/ware-mo-kou/1.jpg",
      "images/shops/ware-mo-kou/2.jpg",
      "images/shops/ware-mo-kou/3.jpg"
    ],
    "attributions": [
      "ずんだもん",
      "Eunice Joung"
    ]
  },
  "n-id-tokyo": {
    "place_id": "ChIJwQWYmKiMGGARb6EHTLTleNM",
    "google_maps_uri": "https://maps.google.com/?cid=15238181901740515695&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA",
    "rating": 4.1,
    "user_rating_count": 25,
    "image_paths": [
      "images/shops/n-id-tokyo/1.jpg",
      "images/shops/n-id-tokyo/2.jpg",
      "images/shops/n-id-tokyo/3.jpg"
    ],
    "attributions": [
      "Thuy B",
      "N id Tokyo"
    ]
  },
  "sullen-tokyo": {
    "place_id": "ChIJec6NyqiMGGARPk5g_Mtt1tk",
    "google_maps_uri": "https://maps.google.com/?cid=15696854274126401086&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA",
    "rating": 4,
    "user_rating_count": 28,
    "image_paths": [
      "images/shops/sullen-tokyo/1.jpg",
      "images/shops/sullen-tokyo/2.jpg",
      "images/shops/sullen-tokyo/3.jpg"
    ],
    "attributions": [
      "SULLEN TOKYO"
    ]
  },
  "globe-specs-shibuya": {
    "place_id": "ChIJqVtCLq-MGGARVvc-7jTeZ74",
    "google_maps_uri": "https://maps.google.com/?cid=13720179108724275030&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA",
    "rating": 3.8,
    "user_rating_count": 114,
    "image_paths": [
      "images/shops/globe-specs-shibuya/1.jpg",
      "images/shops/globe-specs-shibuya/2.jpg",
      "images/shops/globe-specs-shibuya/3.jpg"
    ],
    "attributions": [
      "GLOBE SPECS SHIBUYA STORE",
      "堀江ケニー"
    ]
  },
  "nordisk-camp-supply-shibuya": {
    "place_id": "ChIJ1WA5r4GNGGARLRg1Lrw4bjk",
    "google_maps_uri": "https://maps.google.com/?cid=4138307488480303149&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA",
    "rating": 4.1,
    "user_rating_count": 19,
    "image_paths": [
      "images/shops/nordisk-camp-supply-shibuya/1.jpg",
      "images/shops/nordisk-camp-supply-shibuya/2.jpg",
      "images/shops/nordisk-camp-supply-shibuya/3.jpg"
    ],
    "attributions": [
      "Torben Mauch",
      "NORDISK CAMP SUPPLY STORE SHIBUYA",
      "m h (mr.p)"
    ]
  },
  "roots-to-branches": {
    "place_id": "ChIJvy2fek6LGGAR1Q2ZvqtqX8s",
    "google_maps_uri": "https://maps.google.com/?cid=14654548998356536789&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA",
    "rating": 4.3,
    "user_rating_count": 32,
    "image_paths": [
      "images/shops/roots-to-branches/1.jpg",
      "images/shops/roots-to-branches/2.jpg",
      "images/shops/roots-to-branches/3.jpg"
    ],
    "attributions": [
      "ishiko",
      "Rodney Loh",
      "H G"
    ]
  },
  "so-nakameguro": {
    "place_id": "ChIJBWEY2TaLGGARUo7agjyMqbw",
    "google_maps_uri": "https://maps.google.com/?cid=13594551141715840594&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA",
    "rating": 3.3,
    "user_rating_count": 28,
    "image_paths": [
      "images/shops/so-nakameguro/1.jpg",
      "images/shops/so-nakameguro/2.jpg",
      "images/shops/so-nakameguro/3.jpg"
    ],
    "attributions": [
      "김재현",
      "2 ta",
      "NARU"
    ]
  },
  "1ldk-nakameguro": {
    "place_id": "ChIJ__-jS0-LGGARLaQX137lu7k",
    "google_maps_uri": "https://maps.google.com/?cid=13383543050598851629&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA",
    "rating": 3.6,
    "user_rating_count": 102,
    "image_paths": [
      "images/shops/1ldk-nakameguro/1.jpg",
      "images/shops/1ldk-nakameguro/2.jpg",
      "images/shops/1ldk-nakameguro/3.jpg"
    ],
    "attributions": [
      "MU",
      "朱敏杰",
      "김태훈"
    ]
  },
  "bechics": {
    "place_id": "ChIJuwvA6E2LGGAR6IGwqCfnpho",
    "google_maps_uri": "https://maps.google.com/?cid=1920476448639975912&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA",
    "rating": 3.4,
    "user_rating_count": 32,
    "image_paths": [
      "images/shops/bechics/1.jpg",
      "images/shops/bechics/2.jpg",
      "images/shops/bechics/3.jpg"
    ],
    "attributions": [
      "マタタビの旅",
      "ふかせみつあき",
      "Crown Shief"
    ]
  },
  "best-packing-store": {
    "place_id": "ChIJIZsejE6LGGARwb4A0dcMQNU",
    "google_maps_uri": "https://maps.google.com/?cid=15366296049652121281&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA",
    "rating": 3.8,
    "user_rating_count": 46,
    "image_paths": [
      "images/shops/best-packing-store/1.jpg",
      "images/shops/best-packing-store/2.jpg",
      "images/shops/best-packing-store/3.jpg"
    ],
    "attributions": [
      "ふかせみつあき",
      "阿綸鎂",
      "奈塚Q弥"
    ]
  },
  "elementary-store-bin": {
    "place_id": "ChIJ84BVBE6LGGARJ9U32e_6t2U",
    "google_maps_uri": "https://maps.google.com/?cid=7329602826617214247&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA",
    "rating": 4.7,
    "user_rating_count": 27,
    "image_paths": [
      "images/shops/elementary-store-bin/1.jpg",
      "images/shops/elementary-store-bin/2.jpg",
      "images/shops/elementary-store-bin/3.jpg"
    ],
    "attributions": [
      "ELEMENTARY STORE BIN",
      "Tokyo BIN",
      "K K"
    ]
  },
  "vendor": {
    "place_id": "ChIJm0RqfE6LGGARVmbho6BZJsY",
    "google_maps_uri": "https://maps.google.com/?cid=14278198215103833686&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA",
    "rating": 4.2,
    "user_rating_count": 98,
    "image_paths": [
      "images/shops/vendor/1.jpg",
      "images/shops/vendor/2.jpg",
      "images/shops/vendor/3.jpg"
    ],
    "attributions": [
      "sippo f",
      "n a"
    ]
  },
  "the-galley-box": {
    "place_id": "ChIJf9IrJ5qLGGARUkAG28Ou50A",
    "google_maps_uri": "https://maps.google.com/?cid=4676898894264025170&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA",
    "rating": 4.5,
    "user_rating_count": 4,
    "image_paths": [
      "images/shops/the-galley-box/1.jpg",
      "images/shops/the-galley-box/2.jpg"
    ],
    "attributions": [
      "Pasta"
    ]
  },
  "coper": {
    "place_id": "ChIJ__9bpkiLGGAR2Orev2w5s6E",
    "google_maps_uri": "https://maps.google.com/?cid=11651719800175913688&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA",
    "rating": 4.4,
    "user_rating_count": 10,
    "image_paths": [
      "images/shops/coper/1.jpg",
      "images/shops/coper/2.jpg",
      "images/shops/coper/3.jpg"
    ],
    "attributions": [
      "32GBのSDカード",
      "t"
    ]
  },
  "fifth-general-store": {
    "place_id": "ChIJISevBkmLGGARqQKpGHfKcSY",
    "google_maps_uri": "https://maps.google.com/?cid=2770217858673214121&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA",
    "rating": 4,
    "user_rating_count": 52,
    "image_paths": [
      "images/shops/fifth-general-store/1.jpg",
      "images/shops/fifth-general-store/2.jpg",
      "images/shops/fifth-general-store/3.jpg"
    ],
    "attributions": [
      "藤根理香",
      "Fifth General Store",
      "32GBのSDカード"
    ]
  },
  "the-library-omotesando": {
    "place_id": "ChIJXwhXNViNGGARUk0gPtfBrhs",
    "google_maps_uri": "https://maps.google.com/?cid=1994744815176142162&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA",
    "rating": 5,
    "user_rating_count": 75,
    "image_paths": [
      "images/shops/the-library-omotesando/1.jpg",
      "images/shops/the-library-omotesando/2.jpg",
      "images/shops/the-library-omotesando/3.jpg"
    ],
    "attributions": [
      "Clara",
      "廣木潤"
    ]
  },
  "lechoppe-aoyama": {
    "place_id": "ChIJhTrMTmCLGGAReCbQUeNOzYo",
    "google_maps_uri": "https://maps.google.com/?cid=10001737085696878200&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA",
    "rating": 3.3,
    "user_rating_count": 59,
    "image_paths": [
      "images/shops/lechoppe-aoyama/1.jpg",
      "images/shops/lechoppe-aoyama/2.jpg",
      "images/shops/lechoppe-aoyama/3.jpg"
    ],
    "attributions": [
      "Zee K",
      "HAYATO"
    ]
  },
  "h-beauty-and-youth": {
    "place_id": "ChIJ5VubxWGLGGARsxRhDl45NAI",
    "google_maps_uri": "https://maps.google.com/?cid=158814962995762355&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA",
    "rating": 4.4,
    "user_rating_count": 258,
    "image_paths": [
      "images/shops/h-beauty-and-youth/1.jpg",
      "images/shops/h-beauty-and-youth/2.jpg",
      "images/shops/h-beauty-and-youth/3.jpg"
    ],
    "attributions": [
      "エイチ ビューティー＆ユース",
      "EijiK",
      "李エイキ"
    ]
  },
  "super-a-market-aoyama": {
    "place_id": "ChIJtbB7KWCLGGARB2GIKJMhAEg",
    "google_maps_uri": "https://maps.google.com/?cid=5188183686654746887&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA",
    "rating": 4.1,
    "user_rating_count": 54,
    "image_paths": [
      "images/shops/super-a-market-aoyama/1.jpg",
      "images/shops/super-a-market-aoyama/2.jpg",
      "images/shops/super-a-market-aoyama/3.jpg"
    ],
    "attributions": [
      "Kaz Σ3",
      "スーパー エー マーケット 青山"
    ]
  },
  "district-united-arrows": {
    "place_id": "ChIJwSRyoqaMGGARYx0E4d_BiuY",
    "google_maps_uri": "https://maps.google.com/?cid=16612303342806506851&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA",
    "rating": 4.5,
    "user_rating_count": 51,
    "image_paths": [
      "images/shops/district-united-arrows/1.jpg",
      "images/shops/district-united-arrows/2.jpg",
      "images/shops/district-united-arrows/3.jpg"
    ],
    "attributions": [
      "Arseni I.",
      "ディストリクト ユナイテッドアローズ"
    ]
  },
  "1ldk-aoyama": {
    "place_id": "ChIJDT_cnWaLGGARbX7OBQ2Pv5o",
    "google_maps_uri": "https://maps.google.com/?cid=11150788488487403117&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA",
    "rating": 4.1,
    "user_rating_count": 52,
    "image_paths": [
      "images/shops/1ldk-aoyama/1.jpg",
      "images/shops/1ldk-aoyama/2.jpg",
      "images/shops/1ldk-aoyama/3.jpg"
    ],
    "attributions": [
      "Key jetsetter",
      "U_G",
      "BURI DOG"
    ]
  },
  "edition-omotesando-hills": {
    "place_id": "ChIJzweLeKGMGGAR6C1ZCdCSB6A",
    "google_maps_uri": "https://maps.google.com/?cid=11531346793113136616&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA",
    "rating": 3.6,
    "user_rating_count": 37,
    "image_paths": [
      "images/shops/edition-omotesando-hills/1.jpg",
      "images/shops/edition-omotesando-hills/2.jpg",
      "images/shops/edition-omotesando-hills/3.jpg"
    ],
    "attributions": [
      "エディション 表参道ヒルズ店",
      "하상렬"
    ]
  },
  "adelaide": {
    "place_id": "ChIJVVWV06OMGGARw3OZRs3Af4Q",
    "google_maps_uri": "https://maps.google.com/?cid=9547561722934031299&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA",
    "rating": 4,
    "user_rating_count": 22,
    "image_paths": [
      "images/shops/adelaide/1.jpg",
      "images/shops/adelaide/2.jpg",
      "images/shops/adelaide/3.jpg"
    ],
    "attributions": [
      "Kaz Σ3",
      "ADDITION ADELAIDE",
      "Vicious"
    ]
  },
  "international-gallery-beams": {
    "place_id": "ChIJm5OZNqOMGGARCvdtIW4fJeI",
    "google_maps_uri": "https://maps.google.com/?cid=16295465384577726218&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA",
    "rating": 3.6,
    "user_rating_count": 104,
    "image_paths": [
      "images/shops/international-gallery-beams/1.jpg",
      "images/shops/international-gallery-beams/2.jpg",
      "images/shops/international-gallery-beams/3.jpg"
    ],
    "attributions": [
      "ビームスF／インターナショナルギャラリー ビームス",
      "Nadjib Achaibou"
    ]
  },
  "lift-daikanyama": {
    "place_id": "ChIJFeu1Ht-LGGARxvmo6yDlk0A",
    "google_maps_uri": "https://maps.google.com/?cid=4653314769559288262&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA",
    "rating": 4.9,
    "user_rating_count": 20,
    "image_paths": [
      "images/shops/lift-daikanyama/1.jpg",
      "images/shops/lift-daikanyama/2.jpg",
      "images/shops/lift-daikanyama/3.jpg"
    ],
    "attributions": [
      "Lift DAIKANYAMA"
    ]
  },
  "haunt-daikanyama": {
    "place_id": "ChIJP0fi2U-LGGARGKLHjWQqnDs",
    "google_maps_uri": "https://maps.google.com/?cid=4295354755968377368&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA",
    "rating": 3.1,
    "user_rating_count": 37,
    "image_paths": [
      "images/shops/haunt-daikanyama/1.jpg",
      "images/shops/haunt-daikanyama/2.jpg",
      "images/shops/haunt-daikanyama/3.jpg"
    ],
    "attributions": [
      "Sylvia Kung",
      "HAUNT"
    ]
  },
  "forget-me-nots-daikanyama": {
    "place_id": "ChIJ0YeRK9GLGGAR_GShHNIwNAo",
    "google_maps_uri": "https://maps.google.com/?cid=735266318149838076&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA",
    "rating": 2.8,
    "user_rating_count": 13,
    "image_paths": [
      "images/shops/forget-me-nots-daikanyama/1.jpg",
      "images/shops/forget-me-nots-daikanyama/2.jpg",
      "images/shops/forget-me-nots-daikanyama/3.jpg"
    ],
    "attributions": [
      "Umihito Kusama",
      "Forget-me-nots 代官山本店"
    ]
  },
  "select-shop-o-daikanyama": {
    "place_id": "ChIJ0zrjrrOLGGARDjaHmtMJDRU",
    "google_maps_uri": "https://maps.google.com/?cid=1516879453929027086&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA",
    "rating": 2.7,
    "user_rating_count": 57,
    "image_paths": [
      "images/shops/select-shop-o-daikanyama/1.jpg",
      "images/shops/select-shop-o-daikanyama/2.jpg",
      "images/shops/select-shop-o-daikanyama/3.jpg"
    ],
    "attributions": [
      "ふかせみつあき",
      "O 代官山 本店"
    ]
  },
  "high-standard-daikanyama": {
    "place_id": "ChIJlVmtgE-LGGARLhFj85CzByo",
    "google_maps_uri": "https://maps.google.com/?cid=3028586709569966382&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA",
    "rating": 4.6,
    "user_rating_count": 43,
    "image_paths": [
      "images/shops/high-standard-daikanyama/1.jpg",
      "images/shops/high-standard-daikanyama/2.jpg",
      "images/shops/high-standard-daikanyama/3.jpg"
    ],
    "attributions": [
      "ハイ！スタンダード (HIGH! STANDARD)",
      "genya otsuki",
      "Mickson Wong"
    ]
  },
  "studious-mens-harajuku": {
    "place_id": "ChIJtZd6CqOMGGARHkUIeayi5Rk",
    "google_maps_uri": "https://maps.google.com/?cid=1866076482263598366&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA",
    "rating": 2.9,
    "user_rating_count": 106,
    "image_paths": [
      "images/shops/studious-mens-harajuku/1.jpg",
      "images/shops/studious-mens-harajuku/2.jpg",
      "images/shops/studious-mens-harajuku/3.jpg"
    ],
    "attributions": [
      "STUDIOUS MENS 原宿本店"
    ]
  },
  "nubian-harajuku": {
    "place_id": "ChIJq_X9EqOMGGARqNStPwPCqZU",
    "google_maps_uri": "https://maps.google.com/?cid=10784364101924410536&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA",
    "rating": 4.1,
    "user_rating_count": 178,
    "image_paths": [
      "images/shops/nubian-harajuku/1.jpg",
      "images/shops/nubian-harajuku/2.jpg",
      "images/shops/nubian-harajuku/3.jpg"
    ],
    "attributions": [
      "s s",
      "NUBIAN HARAJUKU",
      "Rexton Wendell"
    ]
  },
  "maidens-shop": {
    "place_id": "ChIJjxWVZ72MGGARfp4D3jrwNUI",
    "google_maps_uri": "https://maps.google.com/?cid=4770983515892457086&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA",
    "rating": 4.4,
    "user_rating_count": 46,
    "image_paths": [
      "images/shops/maidens-shop/1.jpg",
      "images/shops/maidens-shop/2.jpg",
      "images/shops/maidens-shop/3.jpg"
    ],
    "attributions": [
      "stefan",
      "Kaz Σ3",
      "Nok"
    ]
  },
  "freshservice-headquarters": {
    "place_id": "ChIJVVX525eMGGARf40SjG9S3os",
    "google_maps_uri": "https://maps.google.com/?cid=10078583655146622335&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA",
    "rating": 4.2,
    "user_rating_count": 32,
    "image_paths": [
      "images/shops/freshservice-headquarters/1.jpg",
      "images/shops/freshservice-headquarters/2.jpg",
      "images/shops/freshservice-headquarters/3.jpg"
    ],
    "attributions": [
      "FreshService headquarters",
      "Satomi Tada"
    ]
  },
  "lantiki-centraaaaal": {
    "place_id": "ChIJ_x0y56CMGGARWwsmupp1VnM",
    "google_maps_uri": "https://maps.google.com/?cid=8310959469767297883&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA",
    "rating": 4,
    "user_rating_count": 32,
    "image_paths": [
      "images/shops/lantiki-centraaaaal/1.jpg",
      "images/shops/lantiki-centraaaaal/2.jpg",
      "images/shops/lantiki-centraaaaal/3.jpg"
    ],
    "attributions": [
      "奈塚Q弥",
      "LANTIKI CENTRAAAAAL TOKYO"
    ]
  },
  "estnation-roppongi": {
    "place_id": "ChIJZdz3VXaLGGARMv4sJSSDcds",
    "google_maps_uri": "https://maps.google.com/?cid=15812563957940289074&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA",
    "rating": 4.2,
    "user_rating_count": 289,
    "image_paths": [
      "images/shops/estnation-roppongi/1.jpg",
      "images/shops/estnation-roppongi/2.jpg",
      "images/shops/estnation-roppongi/3.jpg"
    ],
    "attributions": [
      "中村文則",
      "エストネーション六本木ヒルズ店",
      "S W"
    ]
  },
  "restir-nogizaka": {
    "place_id": "ChIJKV_q1H6LGGARTLcatRC8iOQ",
    "google_maps_uri": "https://maps.google.com/?cid=16467618817424144204&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA",
    "rating": 3.8,
    "user_rating_count": 34,
    "image_paths": [
      "images/shops/restir-nogizaka/1.jpg",
      "images/shops/restir-nogizaka/2.jpg",
      "images/shops/restir-nogizaka/3.jpg"
    ],
    "attributions": [
      "荒井志保（ライアンまま）",
      "yuchi",
      "이창희"
    ]
  },
  "nepenthes-tokyo": {
    "place_id": "ChIJR2u43aCMGGARTngBnAYnBqk",
    "google_maps_uri": "https://maps.google.com/?cid=12179465151610714190&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA",
    "rating": 4,
    "user_rating_count": 141,
    "image_paths": [
      "images/shops/nepenthes-tokyo/1.jpg",
      "images/shops/nepenthes-tokyo/2.jpg",
      "images/shops/nepenthes-tokyo/3.jpg"
    ],
    "attributions": [
      "Masa Ueda",
      "Atsushi SENTO",
      "yuchi"
    ]
  },
  "arts-and-science-aoyama": {
    "place_id": "ChIJCR_54WOLGGARmZjWvHKCHac",
    "google_maps_uri": "https://maps.google.com/?cid=12041924407964637337&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA",
    "rating": 3.5,
    "user_rating_count": 10,
    "image_paths": [],
    "attributions": []
  },
  "hedy-daikanyama": {
    "place_id": "ChIJCTtzgk-LGGAR3AoWem58VbQ",
    "google_maps_uri": "https://maps.google.com/?cid=12994429113783945948&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA",
    "rating": 4.9,
    "user_rating_count": 453,
    "image_paths": [
      "images/shops/hedy-daikanyama/1.jpg",
      "images/shops/hedy-daikanyama/2.jpg",
      "images/shops/hedy-daikanyama/3.jpg"
    ],
    "attributions": [
      "Hedy Daikanyama Vintage shop Tokyo",
      "Xiaofan Wu"
    ]
  },
  "vintage-qoo-tokyo": {
    "place_id": "ChIJ52hyb9iNGGAREupSSr9e5Eo",
    "google_maps_uri": "https://maps.google.com/?cid=5396542429175409170&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA",
    "rating": 4.9,
    "user_rating_count": 5066,
    "image_paths": [
      "images/shops/vintage-qoo-tokyo/1.jpg",
      "images/shops/vintage-qoo-tokyo/2.jpg",
      "images/shops/vintage-qoo-tokyo/3.jpg"
    ],
    "attributions": [
      "VINTAGE QOO TOKYO"
    ]
  },
  "arts-and-science-marunouchi": {
    "place_id": "ChIJvWV9tvmLGGARqzwHYfZMezQ",
    "google_maps_uri": "https://maps.google.com/?cid=3781700933181193387&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA",
    "rating": 3.2,
    "user_rating_count": 18,
    "image_paths": [
      "images/shops/arts-and-science-marunouchi/1.jpg",
      "images/shops/arts-and-science-marunouchi/2.jpg"
    ],
    "attributions": [
      "⸝⸝",
      "김다정"
    ]
  },
  "dover-street-market-ginza": {
    "place_id": "ChIJCyrxGuaLGGARJWVsJlwEERU",
    "google_maps_uri": "https://maps.google.com/?cid=1517999343228708133&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA",
    "rating": 4.2,
    "user_rating_count": 1427,
    "image_paths": [
      "images/shops/dover-street-market-ginza/1.jpg",
      "images/shops/dover-street-market-ginza/2.jpg",
      "images/shops/dover-street-market-ginza/3.jpg"
    ],
    "attributions": [
      "にゃんこゴールド",
      "s s",
      "일비"
    ]
  },
  "beams-ginza": {
    "place_id": "ChIJnQkV0uWLGGARSmJCrTTldXM",
    "google_maps_uri": "https://maps.google.com/?cid=8319807901044728394&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA",
    "rating": 4.5,
    "user_rating_count": 1531,
    "image_paths": [
      "images/shops/beams-ginza/1.jpg",
      "images/shops/beams-ginza/2.jpg",
      "images/shops/beams-ginza/3.jpg"
    ],
    "attributions": [
      "ビームス 銀座"
    ]
  },
  "ships-ginza": {
    "place_id": "ChIJR61gMeSLGGAR0cw_A8BtPF0",
    "google_maps_uri": "https://maps.google.com/?cid=6718365415585598673&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA",
    "rating": 3.8,
    "user_rating_count": 121,
    "image_paths": [
      "images/shops/ships-ginza/1.jpg",
      "images/shops/ships-ginza/2.jpg",
      "images/shops/ships-ginza/3.jpg"
    ],
    "attributions": [
      "齊藤実",
      "@ Your Service TICK.Y",
      "Available Now"
    ]
  },
  "undercover-ginza-six": {
    "place_id": "ChIJfUtnTuaLGGARAvRVsWhfnTg",
    "google_maps_uri": "https://maps.google.com/?cid=4079521740723975170&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA",
    "rating": 4,
    "user_rating_count": 15,
    "image_paths": [
      "images/shops/undercover-ginza-six/1.jpg",
      "images/shops/undercover-ginza-six/2.jpg",
      "images/shops/undercover-ginza-six/3.jpg"
    ],
    "attributions": [
      "Kaoru Yamazaki (kabo)",
      "OMG vishesh"
    ]
  },
  "soph-ginza-six": {
    "place_id": "ChIJp_yHYwCLGGARUUYj5Qarr-o",
    "google_maps_uri": "https://maps.google.com/?cid=16910923171901949521&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA",
    "rating": 5,
    "user_rating_count": 1,
    "image_paths": [],
    "attributions": []
  },
  "mastermind-tokyo-hibiya": {
    "place_id": "ChIJXRcxO-6LGGARnD-33XdDMTc",
    "google_maps_uri": "https://maps.google.com/?cid=3977034128044801948&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA",
    "rating": 3.4,
    "user_rating_count": 36,
    "image_paths": [
      "images/shops/mastermind-tokyo-hibiya/1.jpg",
      "images/shops/mastermind-tokyo-hibiya/2.jpg",
      "images/shops/mastermind-tokyo-hibiya/3.jpg"
    ],
    "attributions": [
      "sho sugino",
      "Rexton Wendell",
      "Thor James"
    ]
  },
  "tatras-concept-store-hibiya": {
    "place_id": "ChIJXdtvOu6LGGARAuMJhGohRik",
    "google_maps_uri": "https://maps.google.com/?cid=2974101345290281730&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA",
    "rating": 4.3,
    "user_rating_count": 22,
    "image_paths": [
      "images/shops/tatras-concept-store-hibiya/1.jpg",
      "images/shops/tatras-concept-store-hibiya/2.jpg",
      "images/shops/tatras-concept-store-hibiya/3.jpg"
    ],
    "attributions": [
      "YUJI YAMASHITA",
      "日本侍"
    ]
  },
  "hankyu-mens-tokyo": {
    "place_id": "ChIJtYDIYuWLGGAR1GQCeK5D6Xk",
    "google_maps_uri": "https://maps.google.com/?cid=8784626964779656404&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA",
    "rating": 3.9,
    "user_rating_count": 2734,
    "image_paths": [
      "images/shops/hankyu-mens-tokyo/1.jpg",
      "images/shops/hankyu-mens-tokyo/2.jpg",
      "images/shops/hankyu-mens-tokyo/3.jpg"
    ],
    "attributions": [
      "阪急メンズ東京",
      "Manhui Lee"
    ]
  },
  "beams-japan-shinjuku": {
    "place_id": "ChIJUWbOAtuMGGARxbNeo0uzhuo",
    "google_maps_uri": "https://maps.google.com/?cid=16899391789199176645&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA",
    "rating": 4.3,
    "user_rating_count": 1644,
    "image_paths": [
      "images/shops/beams-japan-shinjuku/1.jpg",
      "images/shops/beams-japan-shinjuku/2.jpg",
      "images/shops/beams-japan-shinjuku/3.jpg"
    ],
    "attributions": [
      "ビームス ジャパン",
      "ハニーワッフル",
      "Spencer"
    ]
  },
  "isetan-mens-shinjuku": {
    "place_id": "ChIJSzlrpduMGGARD1J1NHhDgzQ",
    "google_maps_uri": "https://maps.google.com/?cid=3783942295476589071&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA",
    "rating": 4.1,
    "user_rating_count": 3807,
    "image_paths": [
      "images/shops/isetan-mens-shinjuku/1.jpg",
      "images/shops/isetan-mens-shinjuku/2.jpg",
      "images/shops/isetan-mens-shinjuku/3.jpg"
    ],
    "attributions": [
      "K daw",
      "T. K."
    ]
  },
  "wism-shinjuku": {
    "place_id": "ChIJV4v3x9qMGGAR38KxZ5RBKvc",
    "google_maps_uri": "https://maps.google.com/?cid=17810119782040715999&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA",
    "rating": 3.3,
    "user_rating_count": 15,
    "image_paths": [
      "images/shops/wism-shinjuku/1.jpg",
      "images/shops/wism-shinjuku/2.jpg",
      "images/shops/wism-shinjuku/3.jpg"
    ],
    "attributions": [
      "Manhui Lee",
      "にゃんこゴールド"
    ]
  },
  "estnation-yurakucho": {
    "place_id": "ChIJrY8D4u-LGGARU_dn2R68Kl0",
    "google_maps_uri": "https://maps.google.com/?cid=6713385035231655763&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA",
    "rating": 3.9,
    "user_rating_count": 92,
    "image_paths": [
      "images/shops/estnation-yurakucho/1.jpg",
      "images/shops/estnation-yurakucho/2.jpg",
      "images/shops/estnation-yurakucho/3.jpg"
    ],
    "attributions": [
      "エストネーション有楽町店",
      "kotomi “cotty.”",
      "Shahbaz Hussain"
    ]
  },
  "beams-house-marunouchi": {
    "place_id": "ChIJOUOd8vmLGGARauFiuVv3CnY",
    "google_maps_uri": "https://maps.google.com/?cid=8505882819566952810&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA",
    "rating": 3.8,
    "user_rating_count": 183,
    "image_paths": [
      "images/shops/beams-house-marunouchi/1.jpg",
      "images/shops/beams-house-marunouchi/2.jpg",
      "images/shops/beams-house-marunouchi/3.jpg"
    ],
    "attributions": [
      "ビームス ハウス 丸の内",
      "よ（柴犬よしぷー）"
    ]
  },
  "beams-plus-yurakucho": {
    "place_id": "ChIJB8H_EPCLGGARCgrVgWdivDA",
    "google_maps_uri": "https://maps.google.com/?cid=3511790006141520394&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA",
    "rating": 4.8,
    "user_rating_count": 302,
    "image_paths": [
      "images/shops/beams-plus-yurakucho/1.jpg",
      "images/shops/beams-plus-yurakucho/2.jpg",
      "images/shops/beams-plus-yurakucho/3.jpg"
    ],
    "attributions": [
      "齊藤実",
      "Kane Chao",
      "ビームス プラス 丸の内"
    ]
  },
  "the-tokyo-marunouchi": {
    "place_id": "ChIJk7NfTRiLGGAR6LiYBNSHSpE",
    "google_maps_uri": "https://maps.google.com/?cid=10469329628456073448&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA",
    "rating": 3.6,
    "user_rating_count": 22,
    "image_paths": [
      "images/shops/the-tokyo-marunouchi/1.jpg",
      "images/shops/the-tokyo-marunouchi/2.jpg",
      "images/shops/the-tokyo-marunouchi/3.jpg"
    ],
    "attributions": [
      "THE TOKYO 丸の内"
    ]
  },
  "tomorrowland-marunouchi": {
    "place_id": "ChIJoR8MA_qLGGAR6dlwIv7Xloc",
    "google_maps_uri": "https://maps.google.com/?cid=9770233928126355945&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA",
    "rating": 4,
    "user_rating_count": 88,
    "image_paths": [
      "images/shops/tomorrowland-marunouchi/1.jpg",
      "images/shops/tomorrowland-marunouchi/2.jpg",
      "images/shops/tomorrowland-marunouchi/3.jpg"
    ],
    "attributions": [
      "トゥモローランド 丸の内店",
      "Key jetsetter",
      "木村恵"
    ]
  },
  "land-of-tomorrow-marunouchi": {
    "place_id": "ChIJk1E6c_qLGGAR3tyzG5KwvvU",
    "google_maps_uri": "https://maps.google.com/?cid=17707784926443855070&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA",
    "rating": 4.2,
    "user_rating_count": 23,
    "image_paths": [
      "images/shops/land-of-tomorrow-marunouchi/1.jpg",
      "images/shops/land-of-tomorrow-marunouchi/2.jpg",
      "images/shops/land-of-tomorrow-marunouchi/3.jpg"
    ],
    "attributions": [
      "ランド オブ トゥモロー 丸の内店"
    ]
  },
  "le-dome-marunouchi": {
    "place_id": "ChIJmZswGPqLGGARycqJM8cYl-I",
    "google_maps_uri": "https://maps.google.com/?cid=16327546217897249481&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA",
    "rating": 4.1,
    "user_rating_count": 37,
    "image_paths": [
      "images/shops/le-dome-marunouchi/1.jpg",
      "images/shops/le-dome-marunouchi/2.jpg",
      "images/shops/le-dome-marunouchi/3.jpg"
    ],
    "attributions": [
      "Le Dome 丸の内店(EDIFICE/IENA)",
      "清水（及川）まゆみ",
      "s t"
    ]
  }
};
